### PR TITLE
add tenant name and name changes

### PR DESCRIPTION
**Pull request by punkle**

### CODE REVIEW

**Review by Xantier — APPROVED** [review]
Modify the skeleton to point to the correct broker tenant URL also

**Comment by punkle** [comment]
@Xantier I believe I did that. Am I missing something?

**Comment by Xantier** [comment]
> @Xantier I believe I did that. Am I missing something?

GitHub doesn't show any changes to js files
image

**Comment by punkle** [comment]
> > @Xantier I believe I did that. Am I missing something?
> 
> GitHub doesn't show any changes to js files image

I changed the input to the template to set values.tenant to the new roadie.tenantName, so that passes through as the same name to the js templates.

**Pull request merged**
